language: node_js
sudo: false
node_js:
- 7
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bloke . --deploy
deploy:
  skip_cleanup: true
  script:
  - ./deploy.sh
  on:
    branch: master
    repo: DavidKk/blog.davidkk.com
